### PR TITLE
Code changes for adding posix rename.

### LINKED ISSUE #173: posix rename
Hello,

I'm using ssh2-sftp-client v4.2.0.
When doing a "rename", it fails if the target path already exists, which is compliant with the sftp protocol. But, does your module support the "posix rename" extension ? If yes, how can I enable it ? otherwise, have you planned to support it ?

Thanks & regards,
Thomas

### PR DESCRIPTION
**Pull request by jhorbulyk**
Fixes #173 

- Documentation updates are still to be done
- Checking the unit tests are still to be done.

### CODE REVIEW

**Comment by theophilusx** [comment]
OK, thanks for the PR. It looks pretty good, so will pull it into a branch and test, merging into master once I've tested and updated docs. Note that I only released a new version yesterday, so may wait a week or so to let any dust settle before releasing new version.

**Comment by jhorbulyk** [comment]
@theophilusx Your thoughts on releasing a new version today?

**Comment by theophilusx** [comment]
Will release new version tomorrow (Tuesday local time - UTC+10).

**Comment by theophilusx** [comment]
ssh2-sftp-client v5.2.0 released just now. Will take a little time to
get out to all npmjs.com servers.

**Pull request merged**
